apiVersion: skaffold/v2beta18
kind: Config
profiles:
  - name: local
    build:
      local:
        push: true
        useDockerCLI: true
      artifacts:
        - image: nexus.dspace.kt.co.kr/argocd/tbill-bfac
    deploy:
      kubectl:
        manifests:
          - k8s/local/tbill-bfac.yaml
    portForward:
      - resourceType: Service
        resourceName: bill-bfac-svc
        namespace: bill
        port: 8080
        localPort: 9001 # *Optional*

  - name: dev
    build:
      local:
        push: true
      artifacts:
        - image: nexus.dspace.kt.co.kr/argocd/tbill-bfac
          jib:
            args:
              - -DskipTests
              - "-Dgs ${maven_settings}"
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=dev"
            fromImage: nexus.dspace.kt.co.kr/argocd/icistr-sa-jre-runtime:v1.0.0
