spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: local
  application:
    name: icis-samp-dbtodb
  banner:
    location: "classpath:config/app-banner.dat"
  batch:
    job:
      enabled: false
  # Database
  datasource:
    driverClassName: com.tmax.tibero.jdbc.TbDriver
    url: jdbc:tibero:thin:@10.217.139.55:8640:DEVIPTAL
    username: "IPTALOWN"
    password: "Icistr123!"
    hikari:
      pool-name: hikari-cp
      maximum-pool-size: "30"
      minimum-idle: 2
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

engine:
  config:
    thread-cnt: 100

logging:
  config: classpath:log4j2.xml

# app
app-info:
  app-name: "ICIS-SAMP-FILETOFILE"
  log-point: "OM"
  chnl-type: "UI"
  user-id: "91226145"
  org-id: "SPT8050"
  title: "BATCH"
  desc: "BATCH"

  #환경별로 달라지는 정보
  node-ip:  ${NODE_IP}
  pod-ip: ${POD_IP}
  pod-name:  ${POD_NAME}
  node-name: ${NODE_NAME}


# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
