spring:
  mvc:
    throw-exception-if-no-handler-found: true
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  batch:
    jdbc:
      initialize-schema: always
      platform: oracle10g
    job:
      enabled: false
  datasource:
    driverClassName: com.tmax.tibero.jdbc.TbDriver
    url: jdbc:tibero:thin:@10.217.139.55:8640:DEVIPTAL
    username: I91319395
    password: !Dc0324402
    hikari:
      connectionTimeout: 30000
      pool-name: hikari-cp
      maximum-pool-size: 128
      minimum-idle: 24
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

step-info:
  chunkSize: 1000

reader-info:
  methodNm: findAll
  chunkSize: 10
  arguments: null

writer-info:
  methodNm: save
