spring:
  cloud:
    consul:
      enabled: false
  devtools:
    restart:
      enabled: false
  mvc:
    throw-exception-if-no-handler-found: true
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  batch:
    jdbc:
      initialize-schema: always
      platform: oracle10g
    job:
      enabled: false
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql:@211.34.231.81:5432:bitnami_airflow
    username: "bn_airflow"
    password: "bitnami_airflow"
    hikari:
      connectionTimeout: 30000
      pool-name: hikari-cp
      maximum-pool-size: 128
      minimum-idle: 24
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

step-info:
  chunkSize: 1000

reader-info:
  methodNm: findAll
  chunkSize: 10
  arguments: null

writer-info:
  methodNm: save
